### ISSUE TITLE
エクセルプログラム作成

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/ExcelInput#1]
processingでエクセルファイルを読み込みなさい。
具体的にはエクセルに座標を入力しておき、その座標に四角形が表示されるようにしなさい。

**Comment by Okuya** [comment]
一日経ったのでヒントを書いときます。

このissueのタイトルから察するに、ちょっと勘違いしてそうなのですが、今回使うべきファイルの形式は.csvです。
エクセルだけど.xlsファイルじゃないです。csvの作成と編集にエクセルを使います。

設定ファイルとして読んだり、計算結果を書いたり、プログラマはcsvファイルを使うことが多いです。

**Comment by hungrykirby** [comment]
@Okuya 
ありがとうございます。僕はとりあえずできています。
今は西村に解かせている段階です。
調べたところXlsReaderをimportすれば、.xlsを扱えるようですが(まだ未確認)、.xlsを使うのは一般的ではないという解釈でよろしいでしょうか？
