### ISSUE TITLE
プログラムをさらに改良してください。

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/ExcelInput#4]
csvファイルに二つの座標、一つの数値を入力したものを作成し、その数値フレームで二つの座標を行き来する四角形を描いてください。

**Comment by Okuya** [comment]
このissueはもっと具体的なタイトルに変更した方がいいです。
僕だったら「アニメーションの実装」にします。

**Comment by hungrykirby** [comment]
@Okuya 
ありがとうございます。
